--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	26-05-20 01:50:38 
--  Relational Database:       	PUB400 
--  Standards Option:          	Db2 for i 
  
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","DETRI" ; 
  
CREATE FUNCTION DETRI1.OBTIENE_EMPLEADOS ( 
	RUTA VARCHAR(252) ) 
	RETURNS TABLE ( 
	ID_EMPLEADO INTEGER , 
	NOMBRE_EMPLEADO VARCHAR(30) , 
	PRIMER_APELLIDO VARCHAR(30) , 
	SEGUNDO_APELLIDO VARCHAR(30) , 
	CORREO_EMPLEADO VARCHAR(30) , 
	PUESTO_EMPLEADO CHAR(2) , 
	EDAD_EMPLEADO INTEGER )   
	LANGUAGE SQL 
	SPECIFIC DETRI1.OBTIENE_EMPLEADOS 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	NO EXTERNAL ACTION 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = DETRI1 , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
RETURN SELECT T . "id" , T . "nombre" , T . "apellido1" , T . "apellido2" , T . "correo" , 
T . "puesto" , T . "edad" 
FROM JSON_TABLE ( GET_CLOB_FROM_FILE ( RUTA ) , '$' 
COLUMNS ( NESTED '$.PLANILLA[*]' 
COLUMNS ( "id" INTEGER , 
"nombre" VARCHAR ( 30 ) , 
"apellido1" VARCHAR ( 30 ) , 
"apellido2" VARCHAR ( 30 ) , 
"correo" VARCHAR ( 30 ) , 
"puesto" CHAR ( 2 ) , 
"edad" INTEGER ) ) 
) T ; 
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC FUNCTION DETRI1.OBTIENE_EMPLEADOS 
TO DETRI WITH GRANT OPTION ; 
  
