--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	26-05-20 01:52:19 
--  Relational Database:       	PUB400 
--  Standards Option:          	Db2 for i 
  
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","DETRI" ; 
  
CREATE PROCEDURE DETRI1.GRABA_PROVINCIA_IFS ( 
	IN RUTA VARCHAR(252) ) 
	LANGUAGE SQL 
	SPECIFIC DETRI1.GRABA_PROVINCIA_IFS 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = DETRI1 , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
DECLARE VOBJJSON CLOB ; 
  
-- Se crea el JSON en la IFS 
CALL IFS_WRITE_UTF8 ( PATH_NAME => RUTA , 
LINE => '' , 
OVERWRITE => 'REPLACE' , 
END_OF_LINE => 'NONE' ) ; 
  
-- Se asigna el Objeto JSON 
SET VOBJJSON = ( SELECT JSON_OBJECT ( KEY 'PROVINCIAS' VALUE 
JSON_ARRAYAGG ( JSON_OBJECT ( KEY 'ID' VALUE ID_PROVINCIA , 
KEY 'PROVINCIA' VALUE TRIM ( NOMBRE_PROVINCIA ) ) ) 
) AS OBJJSON 
FROM SISPROV ) ; 
  
CALL IFS_WRITE_UTF8 ( PATH_NAME => RUTA , 
LINE => VOBJJSON ) ; 
  
END  ; 
  
COMMENT ON SPECIFIC PROCEDURE DETRI1.GRABA_PROVINCIA_IFS 
	IS 'PROCEDIMIENTO PARA EXPORTAR JSON EN IFS' ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE DETRI1.GRABA_PROVINCIA_IFS 
TO DETRI WITH GRANT OPTION ; 
  
